name: build

on: [push, pull_request]

jobs:
  build_linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build an Example
      run: |
        ./cmake-easyinstall --prefix=$HOME git+https://github.com/openPMD/openPMD-api.git

  build_linux_sudo:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build an Example
      run: |
        export CEI_SUDO="sudo"
        ./cmake-easyinstall git+https://github.com/openPMD/openPMD-api.git

  build_macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build an Example
      run: |
        ./cmake-easyinstall --prefix=$HOME git+https://github.com/openPMD/openPMD-api.git

  build_windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build an Example
      shell: bash
      run: |
        ./cmake-easyinstall --prefix="C:\\\\Program Files\PNGwriter" git+https://github.com/openPMD/openPMD-api.git
