name: build

on: [push, pull_request]

jobs:
  style:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build an Example
      run: |
        ./cmake-easyinstall git+https://github.com/danmar/cppcheck.git \
          -DCMAKE_INSTALL_PREFIX=$HOME -DBUILD_TESTS=OFF
        $HOME/bin/cppcheck --help
