name: build

on: [push, pull_request]

jobs:
  style:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build an Example
      run: |
        ./cmake-easyinstall --prefix=$HOME git+https://github.com/danmar/cppcheck.git \
          -DBUILD_TESTS=OFF
        $HOME/bin/cppcheck --help
